In [28]:
import pandas as pd
import matplotlib.pyplot as plt

# Load data
df = pd.read_csv("Players.csv")
df

,Unnamed: 0,Player,height,weight,collage,born,birth_city,birth_state
0,0,Curly Armstrong,180.0,77.0,Indiana University,1918.0,NaN,NaN
1,1,Cliff Barker,188.0,83.0,University of Kentucky,1921.0,Yorktown,Indiana
2,2,Leo Barnhorst,193.0,86.0,University of Notre Dame,1924.0,NaN,NaN
3,3,Ed Bartels,196.0,88.0,North Carolina State University,1925.0,NaN,NaN
4,4,Ralph Beard,178.0,79.0,University of Kentucky,1927.0,Hardinsburg,Kentucky
...,...,...,...,...,...,...,...,...
3917,3917,Troy Williams,198.0,97.0,South Carolina State University,1969.0,Columbia,South Carolina
3918,3918,Kyle Wiltjer,208.0,108.0,Gonzaga University,1992.0,Portland,Oregon
3919,3919,Stephen Zimmerman,213.0,108.0,"University of Nevada, Las Vegas",1996.0,Hendersonville,Tennessee
3920,3920,Paul Zipser,203.0,97.0,NaN,1994.0,Heidelberg,Germany
3921,3921,Ivica Zubac,216.0,120.0,NaN,1997.0,Mostar,Bosnia and Herzegovina

In [29]:
# Load data
df2 = pd.read_csv("player_data.csv")
df2

,name,year_start,year_end,position,height,weight,birth_date,college
0,Alaa Abdelnaby,1991,1995,F-C,6-10,240.0,"June 24, 1968",Duke University
1,Zaid Abdul-Aziz,1969,1978,C-F,6-9,235.0,"April 7, 1946",Iowa State University
2,Kareem Abdul-Jabbar,1970,1989,C,7-2,225.0,"April 16, 1947","University of California, Los Angeles"
3,Mahmoud Abdul-Rauf,1991,2001,G,6-1,162.0,"March 9, 1969",Louisiana State University
4,Tariq Abdul-Wahad,1998,2003,F,6-6,223.0,"November 3, 1974",San Jose State University
...,...,...,...,...,...,...,...,...
4545,Ante Zizic,2018,2018,F-C,6-11,250.0,"January 4, 1997",NaN
4546,Jim Zoet,1983,1983,C,7-1,240.0,"December 20, 1953",Kent State University
4547,Bill Zopf,1971,1971,G,6-1,170.0,"June 7, 1948",Duquesne University
4548,Ivica Zubac,2017,2018,C,7-1,265.0,"March 18, 1997",NaN
4549,Matt Zunic,1949,1949,G-F,6-3,195.0,"December 19, 1919",George Washington University

In [30]:
curry_rows = df2[df2['name'] == 'Stephen Curry']
print(curry_rows)

              name  year_start  year_end position height  weight  \
868  Stephen Curry        2010      2018        G    6-3   190.0

         birth_date           college
868  March 14, 1988  Davidson College

In [31]:
# Load data
df3 = pd.read_csv("Seasons_Stats.csv")
df3

,Unnamed: 0,Year,Player,Pos,Age,Tm,G,GS,MP,PER,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,0,1950.0,Curly Armstrong,G-F,31.0,FTW,63.0,NaN,NaN,NaN,...,0.705,NaN,NaN,NaN,176.0,NaN,NaN,NaN,217.0,458.0
1,1,1950.0,Cliff Barker,SG,29.0,INO,49.0,NaN,NaN,NaN,...,0.708,NaN,NaN,NaN,109.0,NaN,NaN,NaN,99.0,279.0
2,2,1950.0,Leo Barnhorst,SF,25.0,CHS,67.0,NaN,NaN,NaN,...,0.698,NaN,NaN,NaN,140.0,NaN,NaN,NaN,192.0,438.0
3,3,1950.0,Ed Bartels,F,24.0,TOT,15.0,NaN,NaN,NaN,...,0.559,NaN,NaN,NaN,20.0,NaN,NaN,NaN,29.0,63.0
4,4,1950.0,Ed Bartels,F,24.0,DNN,13.0,NaN,NaN,NaN,...,0.548,NaN,NaN,NaN,20.0,NaN,NaN,NaN,27.0,59.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24686,24686,2017.0,Cody Zeller,PF,24.0,CHO,62.0,58.0,1725.0,16.7,...,0.679,135.0,270.0,405.0,99.0,62.0,58.0,65.0,189.0,639.0
24687,24687,2017.0,Tyler Zeller,C,27.0,BOS,51.0,5.0,525.0,13.0,...,0.564,43.0,81.0,124.0,42.0,7.0,21.0,20.0,61.0,178.0
24688,24688,2017.0,Stephen Zimmerman,C,20.0,ORL,19.0,0.0,108.0,7.3,...,0.600,11.0,24.0,35.0,4.0,2.0,5.0,3.0,17.0,23.0
24689,24689,2017.0,Paul Zipser,SF,22.0,CHI,44.0,18.0,843.0,6.9,...,0.775,15.0,110.0,125.0,36.0,15.0,16.0,40.0,78.0,240.0
24690,24690,2017.0,Ivica Zubac,C,19.0,LAL,38.0,11.0,609.0,17.0,...,0.653,41.0,118.0,159.0,30.0,14.0,33.0,30.0,66.0,284.0

In [32]:
curry_rows = df3[df3['Player'] == 'Stephen Curry']
print(curry_rows)

       Unnamed: 0    Year         Player Pos   Age   Tm     G    GS      MP  \
20042       20042  2010.0  Stephen Curry  PG  21.0  GSW  80.0  77.0  2896.0
20654       20654  2011.0  Stephen Curry  PG  22.0  GSW  74.0  74.0  2489.0
21236       21236  2012.0  Stephen Curry  PG  23.0  GSW  26.0  23.0   732.0
21798       21798  2013.0  Stephen Curry  PG  24.0  GSW  78.0  78.0  2983.0
22402       22402  2014.0  Stephen Curry  PG  25.0  GSW  78.0  78.0  2846.0
23000       23000  2015.0  Stephen Curry  PG  26.0  GSW  80.0  80.0  2613.0
23633       23633  2016.0  Stephen Curry  PG  27.0  GSW  79.0  79.0  2700.0
24216       24216  2017.0  Stephen Curry  PG  28.0  GSW  79.0  79.0  2638.0

        PER  ...    FT%   ORB    DRB    TRB    AST    STL   BLK    TOV     PF  \
20042  16.3  ...  0.885  48.0  308.0  356.0  472.0  152.0  19.0  243.0  252.0
20654  19.4  ...  0.934  52.0  234.0  286.0  432.0  109.0  20.0  226.0  233.0
21236  21.2  ...  0.809  15.0   73.0   88.0  138.0   39.0   8.0   65.0   62.0
21798  21.3  ...  0.900  59.0  255.0  314.0  539.0  126.0  12.0  240.0  198.0
22402  24.1  ...  0.885  46.0  288.0  334.0  666.0  128.0  14.0  294.0  194.0
23000  28.0  ...  0.914  56.0  285.0  341.0  619.0  163.0  16.0  249.0  158.0
23633  31.5  ...  0.908  68.0  362.0  430.0  527.0  169.0  15.0  262.0  161.0
24216  24.6  ...  0.898  61.0  292.0  353.0  523.0  143.0  17.0  239.0  183.0

          PTS
20042  1399.0
20654  1373.0
21236   383.0
21798  1786.0
22402  1873.0
23000  1900.0
23633  2375.0
24216  1999.0

[8 rows x 53 columns]

In [34]:
scoring_per_position = df3.groupby('Pos')['PTS'].mean()
print(scoring_per_position)

Pos
C         452.378861
C-F       310.028571
C-PF      347.454545
C-SF      259.500000
F          90.056911
F-C       278.518519
F-G       196.683333
G         184.273381
G-F       286.063291
PF        500.177608
PF-C      325.925926
PF-SF     355.200000
PG        509.365103
PG-SF    1022.000000
PG-SG     462.857143
SF        563.556076
SF-PF     454.619048
SF-PG     543.000000
SF-SG     561.900000
SG        562.697360
SG-PF    1152.000000
SG-PG     438.444444
SG-SF     428.692308
Name: PTS, dtype: float64

In [35]:
reb_per_position = df3.groupby('Pos')['TRB'].mean()
print(reb_per_position)

Pos
C        326.033242
C-F      191.450000
C-PF     270.848485
C-SF     175.500000
F         41.494737
F-C      194.513514
F-G       76.791667
G         44.375000
G-F      116.564103
PF       306.686615
PF-C     245.666667
PF-SF    174.640000
PG       129.458882
PG-SF    266.000000
PG-SG    113.214286
SF       222.165280
SF-PF    219.000000
SF-PG    383.000000
SF-SG    184.866667
SG       145.272424
SG-PF    334.666667
SG-PG     93.111111
SG-SF    141.269231
Name: TRB, dtype: float64

In [36]:
ast_per_position = df3.groupby('Pos')['AST'].mean()
print(ast_per_position)

Pos
C         63.040765
C-F       55.542857
C-PF      47.212121
C-SF      37.500000
F         18.008130
F-C       59.259259
F-G       57.350000
G         56.446043
G-F       94.151899
PF        73.245671
PF-C      48.111111
PF-SF     46.120000
PG       225.760327
PG-SF    329.000000
PG-SG    158.714286
SF        96.713982
SF-PF     77.761905
SF-PG    122.000000
SF-SG    110.300000
SG       127.168364
SG-PF    209.666667
SG-PG    151.333333
SG-SF     94.653846
Name: AST, dtype: float64

In [37]:
efficiency_per_decade = df3.groupby('Year')['PER'].mean()
latest_decade = efficiency_per_decade.sort_index().head(10)
print(latest_decade)

Year
1950.0          NaN
1951.0          NaN
1952.0    12.511811
1953.0    11.698742
1954.0    11.893798
1955.0    12.170526
1956.0    12.770476
1957.0    12.372115
1958.0    11.984685
1959.0    13.266364
Name: PER, dtype: float64

In [38]:
efficiency_per_decade = df3.groupby('Year')['PER'].mean()
latest_decade = efficiency_per_decade.sort_index().tail(10)
print(latest_decade)

Year
2008.0    12.034007
2009.0    12.723540
2010.0    12.447140
2011.0    12.199840
2012.0    12.731942
2013.0    12.127972
2014.0    12.200818
2015.0    12.549155
2016.0    13.218166
2017.0    12.728571
Name: PER, dtype: float64

In [39]:
df3['Decade'] = (df3['Year'] // 10) * 10
efficiency_per_decade = df3.groupby('Decade')['PER'].mean()
print(efficiency_per_decade)

Decade
1950.0    12.294468
1960.0    12.760907
1970.0    12.956035
1980.0    12.339528
1990.0    12.478852
2000.0    12.250837
2010.0    12.520420
Name: PER, dtype: float64